### ISSUE TITLE
Can't connect Tammy to Mozilla SSO due to "unknown protocol"

### ISSUE THREAD

**Issue by bjherbison** [nbuechner/tammy-snap#1]
I installed tammy on Ubuntu with "sudo snap install tammy". I put "chat.mozilla.org" on the account creation box (even though I want to use an existing account, not create a new one).

I was sent to https://mozilla.modular.im/_synapse/client/saml2/authn_response which said "Continuing will grant de.connect2x.tammy://localhost/sso access to your account.". The Continue button  did nothing.

From the console:
Prevented navigation to “de.connect2x.tammy://localhost/sso?state=REMOVED&loginToken=REMOVED” due to an unknown protocol.

I'm using Firefox Nightly.

(Since this isn't a SNAP issue I  would have preferred to report this on https://gitlab.com/connect2x/tammy but I don't see a mechanism for doing that.)

**Comment by nbuechner** [comment]
https://gitlab.com/connect2x/tammy/-/issues
